/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ContactMessageId = IDL.Nat;
export const Timestamp = IDL.Int;
export const ContactMessage = IDL.Record({
  'id' : ContactMessageId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const ProductId = IDL.Nat;
export const SubmitReviewArgs = IDL.Record({
  'productId' : ProductId,
  'reviewerName' : IDL.Text,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});
export const ReviewId = IDL.Nat;
export const Review = IDL.Record({
  'id' : ReviewId,
  'createdAt' : Timestamp,
  'productId' : ProductId,
  'reviewerName' : IDL.Text,
  'comment' : IDL.Text,
  'reviewerPrincipal' : IDL.Principal,
  'rating' : IDL.Nat,
});
export const CreateCategoryArgs = IDL.Record({
  'nameHindi' : IDL.Text,
  'sortOrder' : IDL.Nat,
  'icon' : IDL.Text,
  'name' : IDL.Text,
  'colorClass' : IDL.Text,
});
export const CategoryId = IDL.Nat;
export const Category = IDL.Record({
  'id' : CategoryId,
  'nameHindi' : IDL.Text,
  'sortOrder' : IDL.Nat,
  'icon' : IDL.Text,
  'name' : IDL.Text,
  'colorClass' : IDL.Text,
});
export const CreateProductArgs = IDL.Record({
  'inStock' : IDL.Bool,
  'nameHindi' : IDL.Text,
  'packagingType' : IDL.Text,
  'originalPrice' : IDL.Nat,
  'subcategory' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isFreshArrival' : IDL.Bool,
  'stock' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'quantity' : IDL.Text,
  'category' : IDL.Text,
  'brand' : IDL.Text,
  'price' : IDL.Nat,
  'isBestSeller' : IDL.Bool,
  'isTrending' : IDL.Bool,
});
export const Product = IDL.Record({
  'id' : ProductId,
  'inStock' : IDL.Bool,
  'nameHindi' : IDL.Text,
  'packagingType' : IDL.Text,
  'originalPrice' : IDL.Nat,
  'subcategory' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'isFreshArrival' : IDL.Bool,
  'stock' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'quantity' : IDL.Text,
  'category' : IDL.Text,
  'brand' : IDL.Text,
  'rating' : IDL.Float64,
  'price' : IDL.Nat,
  'reviewCount' : IDL.Nat,
  'isBestSeller' : IDL.Bool,
  'isTrending' : IDL.Bool,
});
export const CreateSubcategoryArgs = IDL.Record({
  'categoryId' : CategoryId,
  'nameHindi' : IDL.Text,
  'name' : IDL.Text,
});
export const SubcategoryId = IDL.Nat;
export const Subcategory = IDL.Record({
  'id' : SubcategoryId,
  'categoryId' : CategoryId,
  'nameHindi' : IDL.Text,
  'name' : IDL.Text,
});
export const OrderId = IDL.Nat;
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'confirmed' : IDL.Null,
  'processing' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'upi' : IDL.Null,
  'cashOnDelivery' : IDL.Null,
  'card' : IDL.Null,
  'netBanking' : IDL.Null,
});
export const UserId = IDL.Principal;
export const OrderItem = IDL.Record({
  'productId' : ProductId,
  'productName' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'status' : OrderStatus,
  'paymentMethod' : PaymentMethod,
  'deliveryFee' : IDL.Nat,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'totalAmount' : IDL.Nat,
  'shippingAddress' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
});
export const UserProfile = IDL.Record({
  'principal' : IDL.Principal,
  'displayName' : IDL.Text,
  'createdAt' : Timestamp,
  'email' : IDL.Text,
  'updatedAt' : Timestamp,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const WishlistItem = IDL.Record({
  'productId' : ProductId,
  'addedAt' : Timestamp,
});
export const PlaceOrderArgs = IDL.Record({
  'paymentMethod' : PaymentMethod,
  'deliveryFee' : IDL.Nat,
  'totalAmount' : IDL.Nat,
  'shippingAddress' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
});
export const UpdateCategoryArgs = IDL.Record({
  'id' : CategoryId,
  'nameHindi' : IDL.Text,
  'sortOrder' : IDL.Nat,
  'icon' : IDL.Text,
  'name' : IDL.Text,
  'colorClass' : IDL.Text,
});
export const UpdateProductArgs = IDL.Record({
  'id' : ProductId,
  'inStock' : IDL.Bool,
  'nameHindi' : IDL.Text,
  'packagingType' : IDL.Text,
  'originalPrice' : IDL.Nat,
  'subcategory' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isFreshArrival' : IDL.Bool,
  'stock' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'quantity' : IDL.Text,
  'category' : IDL.Text,
  'brand' : IDL.Text,
  'price' : IDL.Nat,
  'isBestSeller' : IDL.Bool,
  'isTrending' : IDL.Bool,
});
export const UpdateProfileArgs = IDL.Record({
  'displayName' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'addContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [ContactMessage], []),
  'addReview' : IDL.Func([SubmitReviewArgs], [Review], []),
  'addToWishlist' : IDL.Func([ProductId], [IDL.Bool], []),
  'createCategory' : IDL.Func([CreateCategoryArgs], [Category], []),
  'createProduct' : IDL.Func([CreateProductArgs], [Product], []),
  'createSubcategory' : IDL.Func([CreateSubcategoryArgs], [Subcategory], []),
  'deleteCategory' : IDL.Func([CategoryId], [IDL.Bool], []),
  'deleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
  'deleteReview' : IDL.Func([ReviewId, ProductId], [IDL.Bool], []),
  'deleteSubcategory' : IDL.Func([SubcategoryId], [IDL.Bool], []),
  'deleteUserProfile' : IDL.Func([], [IDL.Bool], []),
  'filterProducts' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat), IDL.Opt(IDL.Text)],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getAdminPrincipal' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
  'getCategory' : IDL.Func([CategoryId], [IDL.Opt(Category)], ['query']),
  'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
  'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'getProductReviews' : IDL.Func([ProductId], [IDL.Vec(Review)], ['query']),
  'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getWishlist' : IDL.Func([], [IDL.Vec(WishlistItem)], ['query']),
  'listAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'listBestSellers' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'listCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'listContacts' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'listFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'listFreshArrivals' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'listOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'listProductsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'listSubcategories' : IDL.Func([], [IDL.Vec(Subcategory)], ['query']),
  'listSubcategoriesByCategory' : IDL.Func(
      [CategoryId],
      [IDL.Vec(Subcategory)],
      ['query'],
    ),
  'listTrendingProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'placeOrder' : IDL.Func([PlaceOrderArgs], [Order], []),
  'removeFromWishlist' : IDL.Func([ProductId], [IDL.Bool], []),
  'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'setAdminPrincipal' : IDL.Func([], [], []),
  'updateCategory' : IDL.Func([UpdateCategoryArgs], [IDL.Opt(Category)], []),
  'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [IDL.Opt(Order)], []),
  'updateProduct' : IDL.Func([UpdateProductArgs], [IDL.Opt(Product)], []),
  'updateUserProfile' : IDL.Func([UpdateProfileArgs], [UserProfile], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ContactMessageId = IDL.Nat;
  const Timestamp = IDL.Int;
  const ContactMessage = IDL.Record({
    'id' : ContactMessageId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const ProductId = IDL.Nat;
  const SubmitReviewArgs = IDL.Record({
    'productId' : ProductId,
    'reviewerName' : IDL.Text,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const ReviewId = IDL.Nat;
  const Review = IDL.Record({
    'id' : ReviewId,
    'createdAt' : Timestamp,
    'productId' : ProductId,
    'reviewerName' : IDL.Text,
    'comment' : IDL.Text,
    'reviewerPrincipal' : IDL.Principal,
    'rating' : IDL.Nat,
  });
  const CreateCategoryArgs = IDL.Record({
    'nameHindi' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'icon' : IDL.Text,
    'name' : IDL.Text,
    'colorClass' : IDL.Text,
  });
  const CategoryId = IDL.Nat;
  const Category = IDL.Record({
    'id' : CategoryId,
    'nameHindi' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'icon' : IDL.Text,
    'name' : IDL.Text,
    'colorClass' : IDL.Text,
  });
  const CreateProductArgs = IDL.Record({
    'inStock' : IDL.Bool,
    'nameHindi' : IDL.Text,
    'packagingType' : IDL.Text,
    'originalPrice' : IDL.Nat,
    'subcategory' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isFreshArrival' : IDL.Bool,
    'stock' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'quantity' : IDL.Text,
    'category' : IDL.Text,
    'brand' : IDL.Text,
    'price' : IDL.Nat,
    'isBestSeller' : IDL.Bool,
    'isTrending' : IDL.Bool,
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'inStock' : IDL.Bool,
    'nameHindi' : IDL.Text,
    'packagingType' : IDL.Text,
    'originalPrice' : IDL.Nat,
    'subcategory' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'isFreshArrival' : IDL.Bool,
    'stock' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'quantity' : IDL.Text,
    'category' : IDL.Text,
    'brand' : IDL.Text,
    'rating' : IDL.Float64,
    'price' : IDL.Nat,
    'reviewCount' : IDL.Nat,
    'isBestSeller' : IDL.Bool,
    'isTrending' : IDL.Bool,
  });
  const CreateSubcategoryArgs = IDL.Record({
    'categoryId' : CategoryId,
    'nameHindi' : IDL.Text,
    'name' : IDL.Text,
  });
  const SubcategoryId = IDL.Nat;
  const Subcategory = IDL.Record({
    'id' : SubcategoryId,
    'categoryId' : CategoryId,
    'nameHindi' : IDL.Text,
    'name' : IDL.Text,
  });
  const OrderId = IDL.Nat;
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'confirmed' : IDL.Null,
    'processing' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({
    'upi' : IDL.Null,
    'cashOnDelivery' : IDL.Null,
    'card' : IDL.Null,
    'netBanking' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const OrderItem = IDL.Record({
    'productId' : ProductId,
    'productName' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'status' : OrderStatus,
    'paymentMethod' : PaymentMethod,
    'deliveryFee' : IDL.Nat,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'totalAmount' : IDL.Nat,
    'shippingAddress' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
  });
  const UserProfile = IDL.Record({
    'principal' : IDL.Principal,
    'displayName' : IDL.Text,
    'createdAt' : Timestamp,
    'email' : IDL.Text,
    'updatedAt' : Timestamp,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const WishlistItem = IDL.Record({
    'productId' : ProductId,
    'addedAt' : Timestamp,
  });
  const PlaceOrderArgs = IDL.Record({
    'paymentMethod' : PaymentMethod,
    'deliveryFee' : IDL.Nat,
    'totalAmount' : IDL.Nat,
    'shippingAddress' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
  });
  const UpdateCategoryArgs = IDL.Record({
    'id' : CategoryId,
    'nameHindi' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'icon' : IDL.Text,
    'name' : IDL.Text,
    'colorClass' : IDL.Text,
  });
  const UpdateProductArgs = IDL.Record({
    'id' : ProductId,
    'inStock' : IDL.Bool,
    'nameHindi' : IDL.Text,
    'packagingType' : IDL.Text,
    'originalPrice' : IDL.Nat,
    'subcategory' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isFreshArrival' : IDL.Bool,
    'stock' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'quantity' : IDL.Text,
    'category' : IDL.Text,
    'brand' : IDL.Text,
    'price' : IDL.Nat,
    'isBestSeller' : IDL.Bool,
    'isTrending' : IDL.Bool,
  });
  const UpdateProfileArgs = IDL.Record({
    'displayName' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'addContact' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [ContactMessage],
        [],
      ),
    'addReview' : IDL.Func([SubmitReviewArgs], [Review], []),
    'addToWishlist' : IDL.Func([ProductId], [IDL.Bool], []),
    'createCategory' : IDL.Func([CreateCategoryArgs], [Category], []),
    'createProduct' : IDL.Func([CreateProductArgs], [Product], []),
    'createSubcategory' : IDL.Func([CreateSubcategoryArgs], [Subcategory], []),
    'deleteCategory' : IDL.Func([CategoryId], [IDL.Bool], []),
    'deleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
    'deleteReview' : IDL.Func([ReviewId, ProductId], [IDL.Bool], []),
    'deleteSubcategory' : IDL.Func([SubcategoryId], [IDL.Bool], []),
    'deleteUserProfile' : IDL.Func([], [IDL.Bool], []),
    'filterProducts' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat), IDL.Opt(IDL.Text)],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getAdminPrincipal' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
    'getCategory' : IDL.Func([CategoryId], [IDL.Opt(Category)], ['query']),
    'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
    'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'getProductReviews' : IDL.Func([ProductId], [IDL.Vec(Review)], ['query']),
    'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getWishlist' : IDL.Func([], [IDL.Vec(WishlistItem)], ['query']),
    'listAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'listBestSellers' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'listCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'listContacts' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
    'listFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'listFreshArrivals' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'listOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'listProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'listSubcategories' : IDL.Func([], [IDL.Vec(Subcategory)], ['query']),
    'listSubcategoriesByCategory' : IDL.Func(
        [CategoryId],
        [IDL.Vec(Subcategory)],
        ['query'],
      ),
    'listTrendingProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'placeOrder' : IDL.Func([PlaceOrderArgs], [Order], []),
    'removeFromWishlist' : IDL.Func([ProductId], [IDL.Bool], []),
    'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'setAdminPrincipal' : IDL.Func([], [], []),
    'updateCategory' : IDL.Func([UpdateCategoryArgs], [IDL.Opt(Category)], []),
    'updateOrderStatus' : IDL.Func(
        [OrderId, OrderStatus],
        [IDL.Opt(Order)],
        [],
      ),
    'updateProduct' : IDL.Func([UpdateProductArgs], [IDL.Opt(Product)], []),
    'updateUserProfile' : IDL.Func([UpdateProfileArgs], [UserProfile], []),
  });
};

export const init = ({ IDL }) => { return []; };