/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Category {
  'id' : CategoryId,
  'nameHindi' : string,
  'sortOrder' : bigint,
  'icon' : string,
  'name' : string,
  'colorClass' : string,
}
export type CategoryId = bigint;
export interface ContactMessage {
  'id' : ContactMessageId,
  'name' : string,
  'createdAt' : Timestamp,
  'email' : string,
  'message' : string,
}
export type ContactMessageId = bigint;
export interface CreateCategoryArgs {
  'nameHindi' : string,
  'sortOrder' : bigint,
  'icon' : string,
  'name' : string,
  'colorClass' : string,
}
export interface CreateProductArgs {
  'inStock' : boolean,
  'nameHindi' : string,
  'packagingType' : string,
  'originalPrice' : bigint,
  'subcategory' : string,
  'name' : string,
  'description' : string,
  'isFreshArrival' : boolean,
  'stock' : bigint,
  'imageUrl' : string,
  'isFeatured' : boolean,
  'quantity' : string,
  'category' : string,
  'brand' : string,
  'price' : bigint,
  'isBestSeller' : boolean,
  'isTrending' : boolean,
}
export interface CreateSubcategoryArgs {
  'categoryId' : CategoryId,
  'nameHindi' : string,
  'name' : string,
}
export interface Order {
  'id' : OrderId,
  'status' : OrderStatus,
  'paymentMethod' : PaymentMethod,
  'deliveryFee' : bigint,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'totalAmount' : bigint,
  'shippingAddress' : string,
  'items' : Array<OrderItem>,
}
export type OrderId = bigint;
export interface OrderItem {
  'productId' : ProductId,
  'productName' : string,
  'quantity' : bigint,
  'price' : bigint,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null } |
  { 'processing' : null };
export type PaymentMethod = { 'upi' : null } |
  { 'cashOnDelivery' : null } |
  { 'card' : null } |
  { 'netBanking' : null };
export interface PlaceOrderArgs {
  'paymentMethod' : PaymentMethod,
  'deliveryFee' : bigint,
  'totalAmount' : bigint,
  'shippingAddress' : string,
  'items' : Array<OrderItem>,
}
export interface Product {
  'id' : ProductId,
  'inStock' : boolean,
  'nameHindi' : string,
  'packagingType' : string,
  'originalPrice' : bigint,
  'subcategory' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'isFreshArrival' : boolean,
  'stock' : bigint,
  'imageUrl' : string,
  'isFeatured' : boolean,
  'quantity' : string,
  'category' : string,
  'brand' : string,
  'rating' : number,
  'price' : bigint,
  'reviewCount' : bigint,
  'isBestSeller' : boolean,
  'isTrending' : boolean,
}
export type ProductId = bigint;
export interface Review {
  'id' : ReviewId,
  'createdAt' : Timestamp,
  'productId' : ProductId,
  'reviewerName' : string,
  'comment' : string,
  'reviewerPrincipal' : Principal,
  'rating' : bigint,
}
export type ReviewId = bigint;
export interface Subcategory {
  'id' : SubcategoryId,
  'categoryId' : CategoryId,
  'nameHindi' : string,
  'name' : string,
}
export type SubcategoryId = bigint;
export interface SubmitReviewArgs {
  'productId' : ProductId,
  'reviewerName' : string,
  'comment' : string,
  'rating' : bigint,
}
export type Timestamp = bigint;
export interface UpdateCategoryArgs {
  'id' : CategoryId,
  'nameHindi' : string,
  'sortOrder' : bigint,
  'icon' : string,
  'name' : string,
  'colorClass' : string,
}
export interface UpdateProductArgs {
  'id' : ProductId,
  'inStock' : boolean,
  'nameHindi' : string,
  'packagingType' : string,
  'originalPrice' : bigint,
  'subcategory' : string,
  'name' : string,
  'description' : string,
  'isFreshArrival' : boolean,
  'stock' : bigint,
  'imageUrl' : string,
  'isFeatured' : boolean,
  'quantity' : string,
  'category' : string,
  'brand' : string,
  'price' : bigint,
  'isBestSeller' : boolean,
  'isTrending' : boolean,
}
export interface UpdateProfileArgs {
  'displayName' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export type UserId = Principal;
export interface UserProfile {
  'principal' : Principal,
  'displayName' : string,
  'createdAt' : Timestamp,
  'email' : string,
  'updatedAt' : Timestamp,
  'address' : string,
  'phone' : string,
}
export interface WishlistItem { 'productId' : ProductId, 'addedAt' : Timestamp }
export interface _SERVICE {
  'addContact' : ActorMethod<[string, string, string], ContactMessage>,
  'addReview' : ActorMethod<[SubmitReviewArgs], Review>,
  'addToWishlist' : ActorMethod<[ProductId], boolean>,
  'createCategory' : ActorMethod<[CreateCategoryArgs], Category>,
  'createProduct' : ActorMethod<[CreateProductArgs], Product>,
  'createSubcategory' : ActorMethod<[CreateSubcategoryArgs], Subcategory>,
  'deleteCategory' : ActorMethod<[CategoryId], boolean>,
  'deleteProduct' : ActorMethod<[ProductId], boolean>,
  'deleteReview' : ActorMethod<[ReviewId, ProductId], boolean>,
  'deleteSubcategory' : ActorMethod<[SubcategoryId], boolean>,
  'deleteUserProfile' : ActorMethod<[], boolean>,
  'filterProducts' : ActorMethod<
    [[] | [string], [] | [bigint], [] | [string]],
    Array<Product>
  >,
  'getAdminPrincipal' : ActorMethod<[], [] | [Principal]>,
  'getCategory' : ActorMethod<[CategoryId], [] | [Category]>,
  'getOrder' : ActorMethod<[OrderId], [] | [Order]>,
  'getProduct' : ActorMethod<[ProductId], [] | [Product]>,
  'getProductReviews' : ActorMethod<[ProductId], Array<Review>>,
  'getUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getWishlist' : ActorMethod<[], Array<WishlistItem>>,
  'listAllReviews' : ActorMethod<[], Array<Review>>,
  'listBestSellers' : ActorMethod<[], Array<Product>>,
  'listCategories' : ActorMethod<[], Array<Category>>,
  'listContacts' : ActorMethod<[], Array<ContactMessage>>,
  'listFeaturedProducts' : ActorMethod<[], Array<Product>>,
  'listFreshArrivals' : ActorMethod<[], Array<Product>>,
  'listOrders' : ActorMethod<[], Array<Order>>,
  'listProducts' : ActorMethod<[], Array<Product>>,
  'listProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'listSubcategories' : ActorMethod<[], Array<Subcategory>>,
  'listSubcategoriesByCategory' : ActorMethod<[CategoryId], Array<Subcategory>>,
  'listTrendingProducts' : ActorMethod<[], Array<Product>>,
  'placeOrder' : ActorMethod<[PlaceOrderArgs], Order>,
  'removeFromWishlist' : ActorMethod<[ProductId], boolean>,
  'searchProducts' : ActorMethod<[string], Array<Product>>,
  'setAdminPrincipal' : ActorMethod<[], undefined>,
  'updateCategory' : ActorMethod<[UpdateCategoryArgs], [] | [Category]>,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], [] | [Order]>,
  'updateProduct' : ActorMethod<[UpdateProductArgs], [] | [Product]>,
  'updateUserProfile' : ActorMethod<[UpdateProfileArgs], UserProfile>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];