/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CreateCategoryArgs = IDL.Record({
  'nameHi' : IDL.Text,
  'sortOrder' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'iconEmoji' : IDL.Text,
});
export const CategoryId = IDL.Nat;
export const Category = IDL.Record({
  'id' : CategoryId,
  'nameHi' : IDL.Text,
  'sortOrder' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'iconEmoji' : IDL.Text,
});
export const SubcategoryId = IDL.Nat;
export const CreateProductArgs = IDL.Record({
  'categoryId' : CategoryId,
  'nameEn' : IDL.Text,
  'nameHi' : IDL.Text,
  'inStock' : IDL.Bool,
  'packagingType' : IDL.Text,
  'originalPrice' : IDL.Nat,
  'fatContent' : IDL.Text,
  'description' : IDL.Text,
  'stockCount' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'subcategoryId' : SubcategoryId,
  'brand' : IDL.Text,
  'price' : IDL.Nat,
  'isTrending' : IDL.Bool,
});
export const ProductId = IDL.Nat;
export const Timestamp = IDL.Int;
export const Product = IDL.Record({
  'id' : ProductId,
  'categoryId' : CategoryId,
  'nameEn' : IDL.Text,
  'nameHi' : IDL.Text,
  'inStock' : IDL.Bool,
  'packagingType' : IDL.Text,
  'originalPrice' : IDL.Nat,
  'createdAt' : Timestamp,
  'fatContent' : IDL.Text,
  'description' : IDL.Text,
  'stockCount' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'subcategoryId' : SubcategoryId,
  'brand' : IDL.Text,
  'rating' : IDL.Float64,
  'price' : IDL.Nat,
  'reviewCount' : IDL.Nat,
  'isTrending' : IDL.Bool,
});
export const CreateSubcategoryArgs = IDL.Record({
  'categoryId' : CategoryId,
  'nameHi' : IDL.Text,
  'name' : IDL.Text,
});
export const Subcategory = IDL.Record({
  'id' : SubcategoryId,
  'categoryId' : CategoryId,
  'nameHi' : IDL.Text,
  'name' : IDL.Text,
});
export const OrderId = IDL.Nat;
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'confirmed' : IDL.Null,
  'processing' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'upi' : IDL.Null,
  'cashOnDelivery' : IDL.Null,
  'card' : IDL.Null,
  'netBanking' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'productId' : ProductId,
  'productName' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'customerName' : IDL.Text,
  'status' : OrderStatus,
  'paymentMethod' : PaymentMethod,
  'customerPhone' : IDL.Text,
  'city' : IDL.Text,
  'createdAt' : Timestamp,
  'totalAmount' : IDL.Nat,
  'address' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
  'pincode' : IDL.Text,
});
export const PlaceOrderArgs = IDL.Record({
  'customerName' : IDL.Text,
  'paymentMethod' : PaymentMethod,
  'customerPhone' : IDL.Text,
  'city' : IDL.Text,
  'totalAmount' : IDL.Nat,
  'address' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
  'pincode' : IDL.Text,
});
export const UpdateCategoryArgs = IDL.Record({
  'id' : CategoryId,
  'nameHi' : IDL.Text,
  'sortOrder' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'iconEmoji' : IDL.Text,
});
export const UpdateProductArgs = IDL.Record({
  'id' : ProductId,
  'categoryId' : CategoryId,
  'nameEn' : IDL.Text,
  'nameHi' : IDL.Text,
  'inStock' : IDL.Bool,
  'packagingType' : IDL.Text,
  'originalPrice' : IDL.Nat,
  'fatContent' : IDL.Text,
  'description' : IDL.Text,
  'stockCount' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'subcategoryId' : SubcategoryId,
  'brand' : IDL.Text,
  'price' : IDL.Nat,
  'isTrending' : IDL.Bool,
});

export const idlService = IDL.Service({
  'createCategory' : IDL.Func([CreateCategoryArgs], [Category], []),
  'createProduct' : IDL.Func([CreateProductArgs], [Product], []),
  'createSubcategory' : IDL.Func([CreateSubcategoryArgs], [Subcategory], []),
  'deleteCategory' : IDL.Func([CategoryId], [IDL.Bool], []),
  'deleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
  'deleteSubcategory' : IDL.Func([SubcategoryId], [IDL.Bool], []),
  'filterProducts' : IDL.Func(
      [IDL.Opt(CategoryId), IDL.Opt(IDL.Nat), IDL.Opt(IDL.Text)],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getAdmin' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
  'getCategory' : IDL.Func([CategoryId], [IDL.Opt(Category)], ['query']),
  'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
  'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'listCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'listFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'listOrders' : IDL.Func([], [IDL.Vec(Order)], []),
  'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'listProductsByCategory' : IDL.Func(
      [CategoryId],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'listSubcategories' : IDL.Func([], [IDL.Vec(Subcategory)], ['query']),
  'listSubcategoriesByCategory' : IDL.Func(
      [CategoryId],
      [IDL.Vec(Subcategory)],
      ['query'],
    ),
  'listTrendingProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'placeOrder' : IDL.Func([PlaceOrderArgs], [Order], []),
  'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'setAdmin' : IDL.Func([], [], []),
  'updateCategory' : IDL.Func([UpdateCategoryArgs], [IDL.Opt(Category)], []),
  'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [IDL.Opt(Order)], []),
  'updateProduct' : IDL.Func([UpdateProductArgs], [IDL.Opt(Product)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CreateCategoryArgs = IDL.Record({
    'nameHi' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'iconEmoji' : IDL.Text,
  });
  const CategoryId = IDL.Nat;
  const Category = IDL.Record({
    'id' : CategoryId,
    'nameHi' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'iconEmoji' : IDL.Text,
  });
  const SubcategoryId = IDL.Nat;
  const CreateProductArgs = IDL.Record({
    'categoryId' : CategoryId,
    'nameEn' : IDL.Text,
    'nameHi' : IDL.Text,
    'inStock' : IDL.Bool,
    'packagingType' : IDL.Text,
    'originalPrice' : IDL.Nat,
    'fatContent' : IDL.Text,
    'description' : IDL.Text,
    'stockCount' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'subcategoryId' : SubcategoryId,
    'brand' : IDL.Text,
    'price' : IDL.Nat,
    'isTrending' : IDL.Bool,
  });
  const ProductId = IDL.Nat;
  const Timestamp = IDL.Int;
  const Product = IDL.Record({
    'id' : ProductId,
    'categoryId' : CategoryId,
    'nameEn' : IDL.Text,
    'nameHi' : IDL.Text,
    'inStock' : IDL.Bool,
    'packagingType' : IDL.Text,
    'originalPrice' : IDL.Nat,
    'createdAt' : Timestamp,
    'fatContent' : IDL.Text,
    'description' : IDL.Text,
    'stockCount' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'subcategoryId' : SubcategoryId,
    'brand' : IDL.Text,
    'rating' : IDL.Float64,
    'price' : IDL.Nat,
    'reviewCount' : IDL.Nat,
    'isTrending' : IDL.Bool,
  });
  const CreateSubcategoryArgs = IDL.Record({
    'categoryId' : CategoryId,
    'nameHi' : IDL.Text,
    'name' : IDL.Text,
  });
  const Subcategory = IDL.Record({
    'id' : SubcategoryId,
    'categoryId' : CategoryId,
    'nameHi' : IDL.Text,
    'name' : IDL.Text,
  });
  const OrderId = IDL.Nat;
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'confirmed' : IDL.Null,
    'processing' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({
    'upi' : IDL.Null,
    'cashOnDelivery' : IDL.Null,
    'card' : IDL.Null,
    'netBanking' : IDL.Null,
  });
  const OrderItem = IDL.Record({
    'productId' : ProductId,
    'productName' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'customerName' : IDL.Text,
    'status' : OrderStatus,
    'paymentMethod' : PaymentMethod,
    'customerPhone' : IDL.Text,
    'city' : IDL.Text,
    'createdAt' : Timestamp,
    'totalAmount' : IDL.Nat,
    'address' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
    'pincode' : IDL.Text,
  });
  const PlaceOrderArgs = IDL.Record({
    'customerName' : IDL.Text,
    'paymentMethod' : PaymentMethod,
    'customerPhone' : IDL.Text,
    'city' : IDL.Text,
    'totalAmount' : IDL.Nat,
    'address' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
    'pincode' : IDL.Text,
  });
  const UpdateCategoryArgs = IDL.Record({
    'id' : CategoryId,
    'nameHi' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'iconEmoji' : IDL.Text,
  });
  const UpdateProductArgs = IDL.Record({
    'id' : ProductId,
    'categoryId' : CategoryId,
    'nameEn' : IDL.Text,
    'nameHi' : IDL.Text,
    'inStock' : IDL.Bool,
    'packagingType' : IDL.Text,
    'originalPrice' : IDL.Nat,
    'fatContent' : IDL.Text,
    'description' : IDL.Text,
    'stockCount' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'subcategoryId' : SubcategoryId,
    'brand' : IDL.Text,
    'price' : IDL.Nat,
    'isTrending' : IDL.Bool,
  });
  
  return IDL.Service({
    'createCategory' : IDL.Func([CreateCategoryArgs], [Category], []),
    'createProduct' : IDL.Func([CreateProductArgs], [Product], []),
    'createSubcategory' : IDL.Func([CreateSubcategoryArgs], [Subcategory], []),
    'deleteCategory' : IDL.Func([CategoryId], [IDL.Bool], []),
    'deleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
    'deleteSubcategory' : IDL.Func([SubcategoryId], [IDL.Bool], []),
    'filterProducts' : IDL.Func(
        [IDL.Opt(CategoryId), IDL.Opt(IDL.Nat), IDL.Opt(IDL.Text)],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getAdmin' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
    'getCategory' : IDL.Func([CategoryId], [IDL.Opt(Category)], ['query']),
    'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
    'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'listCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'listFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'listOrders' : IDL.Func([], [IDL.Vec(Order)], []),
    'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'listProductsByCategory' : IDL.Func(
        [CategoryId],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'listSubcategories' : IDL.Func([], [IDL.Vec(Subcategory)], ['query']),
    'listSubcategoriesByCategory' : IDL.Func(
        [CategoryId],
        [IDL.Vec(Subcategory)],
        ['query'],
      ),
    'listTrendingProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'placeOrder' : IDL.Func([PlaceOrderArgs], [Order], []),
    'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'setAdmin' : IDL.Func([], [], []),
    'updateCategory' : IDL.Func([UpdateCategoryArgs], [IDL.Opt(Category)], []),
    'updateOrderStatus' : IDL.Func(
        [OrderId, OrderStatus],
        [IDL.Opt(Order)],
        [],
      ),
    'updateProduct' : IDL.Func([UpdateProductArgs], [IDL.Opt(Product)], []),
  });
};

export const init = ({ IDL }) => { return []; };