/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Category {
  'id' : CategoryId,
  'nameHi' : string,
  'sortOrder' : bigint,
  'name' : string,
  'description' : string,
  'iconEmoji' : string,
}
export type CategoryId = bigint;
export interface CreateCategoryArgs {
  'nameHi' : string,
  'sortOrder' : bigint,
  'name' : string,
  'description' : string,
  'iconEmoji' : string,
}
export interface CreateProductArgs {
  'categoryId' : CategoryId,
  'nameEn' : string,
  'nameHi' : string,
  'inStock' : boolean,
  'packagingType' : string,
  'originalPrice' : bigint,
  'fatContent' : string,
  'description' : string,
  'stockCount' : bigint,
  'imageUrl' : string,
  'isFeatured' : boolean,
  'subcategoryId' : SubcategoryId,
  'brand' : string,
  'price' : bigint,
  'isTrending' : boolean,
}
export interface CreateSubcategoryArgs {
  'categoryId' : CategoryId,
  'nameHi' : string,
  'name' : string,
}
export interface Order {
  'id' : OrderId,
  'customerName' : string,
  'status' : OrderStatus,
  'paymentMethod' : PaymentMethod,
  'customerPhone' : string,
  'city' : string,
  'createdAt' : Timestamp,
  'totalAmount' : bigint,
  'address' : string,
  'items' : Array<OrderItem>,
  'pincode' : string,
}
export type OrderId = bigint;
export interface OrderItem {
  'productId' : ProductId,
  'productName' : string,
  'quantity' : bigint,
  'price' : bigint,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null } |
  { 'processing' : null };
export type PaymentMethod = { 'upi' : null } |
  { 'cashOnDelivery' : null } |
  { 'card' : null } |
  { 'netBanking' : null };
export interface PlaceOrderArgs {
  'customerName' : string,
  'paymentMethod' : PaymentMethod,
  'customerPhone' : string,
  'city' : string,
  'totalAmount' : bigint,
  'address' : string,
  'items' : Array<OrderItem>,
  'pincode' : string,
}
export interface Product {
  'id' : ProductId,
  'categoryId' : CategoryId,
  'nameEn' : string,
  'nameHi' : string,
  'inStock' : boolean,
  'packagingType' : string,
  'originalPrice' : bigint,
  'createdAt' : Timestamp,
  'fatContent' : string,
  'description' : string,
  'stockCount' : bigint,
  'imageUrl' : string,
  'isFeatured' : boolean,
  'subcategoryId' : SubcategoryId,
  'brand' : string,
  'rating' : number,
  'price' : bigint,
  'reviewCount' : bigint,
  'isTrending' : boolean,
}
export type ProductId = bigint;
export interface Subcategory {
  'id' : SubcategoryId,
  'categoryId' : CategoryId,
  'nameHi' : string,
  'name' : string,
}
export type SubcategoryId = bigint;
export type Timestamp = bigint;
export interface UpdateCategoryArgs {
  'id' : CategoryId,
  'nameHi' : string,
  'sortOrder' : bigint,
  'name' : string,
  'description' : string,
  'iconEmoji' : string,
}
export interface UpdateProductArgs {
  'id' : ProductId,
  'categoryId' : CategoryId,
  'nameEn' : string,
  'nameHi' : string,
  'inStock' : boolean,
  'packagingType' : string,
  'originalPrice' : bigint,
  'fatContent' : string,
  'description' : string,
  'stockCount' : bigint,
  'imageUrl' : string,
  'isFeatured' : boolean,
  'subcategoryId' : SubcategoryId,
  'brand' : string,
  'price' : bigint,
  'isTrending' : boolean,
}
export interface _SERVICE {
  'createCategory' : ActorMethod<[CreateCategoryArgs], Category>,
  'createProduct' : ActorMethod<[CreateProductArgs], Product>,
  'createSubcategory' : ActorMethod<[CreateSubcategoryArgs], Subcategory>,
  'deleteCategory' : ActorMethod<[CategoryId], boolean>,
  'deleteProduct' : ActorMethod<[ProductId], boolean>,
  'deleteSubcategory' : ActorMethod<[SubcategoryId], boolean>,
  'filterProducts' : ActorMethod<
    [[] | [CategoryId], [] | [bigint], [] | [string]],
    Array<Product>
  >,
  'getAdmin' : ActorMethod<[], [] | [Principal]>,
  'getCategory' : ActorMethod<[CategoryId], [] | [Category]>,
  'getOrder' : ActorMethod<[OrderId], [] | [Order]>,
  'getProduct' : ActorMethod<[ProductId], [] | [Product]>,
  'listCategories' : ActorMethod<[], Array<Category>>,
  'listFeaturedProducts' : ActorMethod<[], Array<Product>>,
  'listOrders' : ActorMethod<[], Array<Order>>,
  'listProducts' : ActorMethod<[], Array<Product>>,
  'listProductsByCategory' : ActorMethod<[CategoryId], Array<Product>>,
  'listSubcategories' : ActorMethod<[], Array<Subcategory>>,
  'listSubcategoriesByCategory' : ActorMethod<[CategoryId], Array<Subcategory>>,
  'listTrendingProducts' : ActorMethod<[], Array<Product>>,
  'placeOrder' : ActorMethod<[PlaceOrderArgs], Order>,
  'searchProducts' : ActorMethod<[string], Array<Product>>,
  'setAdmin' : ActorMethod<[], undefined>,
  'updateCategory' : ActorMethod<[UpdateCategoryArgs], [] | [Category]>,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], [] | [Order]>,
  'updateProduct' : ActorMethod<[UpdateProductArgs], [] | [Product]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];