/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Product {
    id: ProductId;
    categoryId: CategoryId;
    nameEn: string;
    nameHi: string;
    inStock: boolean;
    packagingType: string;
    originalPrice: bigint;
    createdAt: Timestamp;
    fatContent: string;
    description: string;
    stockCount: bigint;
    imageUrl: string;
    isFeatured: boolean;
    subcategoryId: SubcategoryId;
    brand: string;
    rating: number;
    price: bigint;
    reviewCount: bigint;
    isTrending: boolean;
}
export type SubcategoryId = bigint;
export type Timestamp = bigint;
export interface CreateCategoryArgs {
    nameHi: string;
    sortOrder: bigint;
    name: string;
    description: string;
    iconEmoji: string;
}
export interface Category {
    id: CategoryId;
    nameHi: string;
    sortOrder: bigint;
    name: string;
    description: string;
    iconEmoji: string;
}
export interface OrderItem {
    productId: ProductId;
    productName: string;
    quantity: bigint;
    price: bigint;
}
export interface Order {
    id: OrderId;
    customerName: string;
    status: OrderStatus;
    paymentMethod: PaymentMethod;
    customerPhone: string;
    city: string;
    createdAt: Timestamp;
    totalAmount: bigint;
    address: string;
    items: Array<OrderItem>;
    pincode: string;
}
export interface UpdateProductArgs {
    id: ProductId;
    categoryId: CategoryId;
    nameEn: string;
    nameHi: string;
    inStock: boolean;
    packagingType: string;
    originalPrice: bigint;
    fatContent: string;
    description: string;
    stockCount: bigint;
    imageUrl: string;
    isFeatured: boolean;
    subcategoryId: SubcategoryId;
    brand: string;
    price: bigint;
    isTrending: boolean;
}
export interface CreateSubcategoryArgs {
    categoryId: CategoryId;
    nameHi: string;
    name: string;
}
export interface Subcategory {
    id: SubcategoryId;
    categoryId: CategoryId;
    nameHi: string;
    name: string;
}
export type CategoryId = bigint;
export type ProductId = bigint;
export interface UpdateCategoryArgs {
    id: CategoryId;
    nameHi: string;
    sortOrder: bigint;
    name: string;
    description: string;
    iconEmoji: string;
}
export interface CreateProductArgs {
    categoryId: CategoryId;
    nameEn: string;
    nameHi: string;
    inStock: boolean;
    packagingType: string;
    originalPrice: bigint;
    fatContent: string;
    description: string;
    stockCount: bigint;
    imageUrl: string;
    isFeatured: boolean;
    subcategoryId: SubcategoryId;
    brand: string;
    price: bigint;
    isTrending: boolean;
}
export interface PlaceOrderArgs {
    customerName: string;
    paymentMethod: PaymentMethod;
    customerPhone: string;
    city: string;
    totalAmount: bigint;
    address: string;
    items: Array<OrderItem>;
    pincode: string;
}
export type OrderId = bigint;
export enum OrderStatus {
    shipped = "shipped",
    cancelled = "cancelled",
    pending = "pending",
    delivered = "delivered",
    confirmed = "confirmed",
    processing = "processing"
}
export enum PaymentMethod {
    upi = "upi",
    cashOnDelivery = "cashOnDelivery",
    card = "card",
    netBanking = "netBanking"
}
export interface backendInterface {
    createCategory(args: CreateCategoryArgs): Promise<Category>;
    createProduct(args: CreateProductArgs): Promise<Product>;
    createSubcategory(args: CreateSubcategoryArgs): Promise<Subcategory>;
    deleteCategory(id: CategoryId): Promise<boolean>;
    deleteProduct(id: ProductId): Promise<boolean>;
    deleteSubcategory(id: SubcategoryId): Promise<boolean>;
    filterProducts(categoryId: CategoryId | null, maxPrice: bigint | null, packagingType: string | null): Promise<Array<Product>>;
    getAdmin(): Promise<Principal | null>;
    getCategory(id: CategoryId): Promise<Category | null>;
    getOrder(id: OrderId): Promise<Order | null>;
    getProduct(id: ProductId): Promise<Product | null>;
    listCategories(): Promise<Array<Category>>;
    listFeaturedProducts(): Promise<Array<Product>>;
    listOrders(): Promise<Array<Order>>;
    listProducts(): Promise<Array<Product>>;
    listProductsByCategory(categoryId: CategoryId): Promise<Array<Product>>;
    listSubcategories(): Promise<Array<Subcategory>>;
    listSubcategoriesByCategory(categoryId: CategoryId): Promise<Array<Subcategory>>;
    listTrendingProducts(): Promise<Array<Product>>;
    placeOrder(args: PlaceOrderArgs): Promise<Order>;
    searchProducts(term: string): Promise<Array<Product>>;
    setAdmin(): Promise<void>;
    updateCategory(args: UpdateCategoryArgs): Promise<Category | null>;
    updateOrderStatus(id: OrderId, status: OrderStatus): Promise<Order | null>;
    updateProduct(args: UpdateProductArgs): Promise<Product | null>;
}
import type { Category as _Category, CategoryId as _CategoryId, Order as _Order, OrderId as _OrderId, OrderItem as _OrderItem, OrderStatus as _OrderStatus, PaymentMethod as _PaymentMethod, PlaceOrderArgs as _PlaceOrderArgs, Product as _Product, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createCategory(arg0: CreateCategoryArgs): Promise<Category> {
        if (this.processError) {
            try {
                const result = await this.actor.createCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCategory(arg0);
            return result;
        }
    }
    async createProduct(arg0: CreateProductArgs): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.createProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProduct(arg0);
            return result;
        }
    }
    async createSubcategory(arg0: CreateSubcategoryArgs): Promise<Subcategory> {
        if (this.processError) {
            try {
                const result = await this.actor.createSubcategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSubcategory(arg0);
            return result;
        }
    }
    async deleteCategory(arg0: CategoryId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCategory(arg0);
            return result;
        }
    }
    async deleteProduct(arg0: ProductId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async deleteSubcategory(arg0: SubcategoryId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSubcategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSubcategory(arg0);
            return result;
        }
    }
    async filterProducts(arg0: CategoryId | null, arg1: bigint | null, arg2: string | null): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterProducts(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterProducts(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async getAdmin(): Promise<Principal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdmin();
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdmin();
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCategory(arg0: CategoryId): Promise<Category | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategory(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategory(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrder(arg0: OrderId): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduct(arg0: ProductId): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async listCategories(): Promise<Array<Category>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCategories();
            return result;
        }
    }
    async listFeaturedProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFeaturedProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFeaturedProducts();
            return result;
        }
    }
    async listOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.listOrders();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listOrders();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async listProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProducts();
            return result;
        }
    }
    async listProductsByCategory(arg0: CategoryId): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProductsByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProductsByCategory(arg0);
            return result;
        }
    }
    async listSubcategories(): Promise<Array<Subcategory>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSubcategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSubcategories();
            return result;
        }
    }
    async listSubcategoriesByCategory(arg0: CategoryId): Promise<Array<Subcategory>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSubcategoriesByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSubcategoriesByCategory(arg0);
            return result;
        }
    }
    async listTrendingProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTrendingProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTrendingProducts();
            return result;
        }
    }
    async placeOrder(arg0: PlaceOrderArgs): Promise<Order> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(to_candid_PlaceOrderArgs_n15(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Order_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(to_candid_PlaceOrderArgs_n15(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Order_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchProducts(arg0: string): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchProducts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchProducts(arg0);
            return result;
        }
    }
    async setAdmin(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAdmin();
            return result;
        }
    }
    async updateCategory(arg0: UpdateCategoryArgs): Promise<Category | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCategory(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCategory(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateOrderStatus(arg0: OrderId, arg1: OrderStatus): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n19(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n19(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProduct(arg0: UpdateProductArgs): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_OrderStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Product | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Category]): Category | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : from_candid_Order_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _OrderId;
    customerName: string;
    status: _OrderStatus;
    paymentMethod: _PaymentMethod;
    customerPhone: string;
    city: string;
    createdAt: _Timestamp;
    totalAmount: bigint;
    address: string;
    items: Array<_OrderItem>;
    pincode: string;
}): {
    id: OrderId;
    customerName: string;
    status: OrderStatus;
    paymentMethod: PaymentMethod;
    customerPhone: string;
    city: string;
    createdAt: Timestamp;
    totalAmount: bigint;
    address: string;
    items: Array<OrderItem>;
    pincode: string;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: from_candid_OrderStatus_n9(_uploadFile, _downloadFile, value.status),
        paymentMethod: from_candid_PaymentMethod_n11(_uploadFile, _downloadFile, value.paymentMethod),
        customerPhone: value.customerPhone,
        city: value.city,
        createdAt: value.createdAt,
        totalAmount: value.totalAmount,
        address: value.address,
        items: value.items,
        pincode: value.pincode
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    shipped: null;
} | {
    cancelled: null;
} | {
    pending: null;
} | {
    delivered: null;
} | {
    confirmed: null;
} | {
    processing: null;
}): OrderStatus {
    return "shipped" in value ? OrderStatus.shipped : "cancelled" in value ? OrderStatus.cancelled : "pending" in value ? OrderStatus.pending : "delivered" in value ? OrderStatus.delivered : "confirmed" in value ? OrderStatus.confirmed : "processing" in value ? OrderStatus.processing : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upi: null;
} | {
    cashOnDelivery: null;
} | {
    card: null;
} | {
    netBanking: null;
}): PaymentMethod {
    return "upi" in value ? PaymentMethod.upi : "cashOnDelivery" in value ? PaymentMethod.cashOnDelivery : "card" in value ? PaymentMethod.card : "netBanking" in value ? PaymentMethod.netBanking : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n7(_uploadFile, _downloadFile, x));
}
function to_candid_OrderStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_PlaceOrderArgs_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlaceOrderArgs): _PlaceOrderArgs {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CategoryId | null): [] | [_CategoryId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: string;
    paymentMethod: PaymentMethod;
    customerPhone: string;
    city: string;
    totalAmount: bigint;
    address: string;
    items: Array<OrderItem>;
    pincode: string;
}): {
    customerName: string;
    paymentMethod: _PaymentMethod;
    customerPhone: string;
    city: string;
    totalAmount: bigint;
    address: string;
    items: Array<_OrderItem>;
    pincode: string;
} {
    return {
        customerName: value.customerName,
        paymentMethod: to_candid_PaymentMethod_n17(_uploadFile, _downloadFile, value.paymentMethod),
        customerPhone: value.customerPhone,
        city: value.city,
        totalAmount: value.totalAmount,
        address: value.address,
        items: value.items,
        pincode: value.pincode
    };
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    upi: null;
} | {
    cashOnDelivery: null;
} | {
    card: null;
} | {
    netBanking: null;
} {
    return value == PaymentMethod.upi ? {
        upi: null
    } : value == PaymentMethod.cashOnDelivery ? {
        cashOnDelivery: null
    } : value == PaymentMethod.card ? {
        card: null
    } : value == PaymentMethod.netBanking ? {
        netBanking: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    shipped: null;
} | {
    cancelled: null;
} | {
    pending: null;
} | {
    delivered: null;
} | {
    confirmed: null;
} | {
    processing: null;
} {
    return value == OrderStatus.shipped ? {
        shipped: null
    } : value == OrderStatus.cancelled ? {
        cancelled: null
    } : value == OrderStatus.pending ? {
        pending: null
    } : value == OrderStatus.delivered ? {
        delivered: null
    } : value == OrderStatus.confirmed ? {
        confirmed: null
    } : value == OrderStatus.processing ? {
        processing: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
